using Constriva.Domain.Enums;

namespace Constriva.Application.Features.Obras.DTOs;

public record UpdateObraDto(
    string? Nome,
    TipoObraEnum? Tipo,
    TipoContratoObraEnum? TipoContrato,
    string? NomeCliente,
    Guid? ClienteId,
    string? ResponsavelTecnico,
    string? CreaResponsavel,
    string? Descricao,
    string? Observacoes,
    string? NumeroART,
    string? NumeroRRT,
    string? NumeroAlvara,
    DateTime? ValidadeAlvara,
    double? AreaTotal,
    double? AreaConstruida,
    int? NumeroAndares,
    int? NumeroUnidades,
    decimal? ValorContrato,
    decimal? ValorOrcado,
    DateTime? DataInicioPrevista,
    DateTime? DataFimPrevista,
    DateTime? DataInicioReal,
    DateTime? DataFimReal,
    string? Logradouro,
    string? Numero,
    string? Complemento,
    string? Bairro,
    string? Cidade,
    string? Estado,
    string? Cep,
    double? Latitude,
    double? Longitude,
    string? FotoUrl);
