using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Constriva.Domain.Entities.Common;

namespace Constriva.Infrastructure.Persistence.Configurations.Common;

public class BancoConfiguration : IEntityTypeConfiguration<Banco>
{
    public void Configure(EntityTypeBuilder<Banco> b)
    {
        b.ToTable("Bancos");
        b.HasKey(e => e.Id);
        b.Property(e => e.Codigo).HasMaxLength(3).IsRequired();
        b.Property(e => e.Nome).HasMaxLength(200).IsRequired();
        b.HasIndex(e => e.Codigo).IsUnique();

        b.HasData(
            new Banco { Id = 1, Codigo = "001", Nome = "Banco do Brasil" },
            new Banco { Id = 3, Codigo = "003", Nome = "Banco da Amazônia" },
            new Banco { Id = 4, Codigo = "004", Nome = "Banco do Nordeste do Brasil" },
            new Banco { Id = 10, Codigo = "010", Nome = "Credicoamo" },
            new Banco { Id = 12, Codigo = "012", Nome = "Banco Inbursa" },
            new Banco { Id = 21, Codigo = "021", Nome = "Banestes" },
            new Banco { Id = 24, Codigo = "024", Nome = "Banco Bandepe" },
            new Banco { Id = 25, Codigo = "025", Nome = "Banco Alfa" },
            new Banco { Id = 29, Codigo = "029", Nome = "Banco Itaú Consignado" },
            new Banco { Id = 33, Codigo = "033", Nome = "Banco Santander" },
            new Banco { Id = 36, Codigo = "036", Nome = "Banco Bradesco BBI" },
            new Banco { Id = 37, Codigo = "037", Nome = "Banco do Estado do Pará" },
            new Banco { Id = 40, Codigo = "040", Nome = "Banco Cargill" },
            new Banco { Id = 41, Codigo = "041", Nome = "Banco do Estado do Rio Grande do Sul (Banrisul)" },
            new Banco { Id = 47, Codigo = "047", Nome = "Banco do Estado de Sergipe (Banese)" },
            new Banco { Id = 62, Codigo = "062", Nome = "Hipercard Banco Múltiplo" },
            new Banco { Id = 63, Codigo = "063", Nome = "Banco Bradescard" },
            new Banco { Id = 65, Codigo = "065", Nome = "Banco Lemon" },
            new Banco { Id = 66, Codigo = "066", Nome = "Banco Morgan Stanley" },
            new Banco { Id = 69, Codigo = "069", Nome = "Banco Crefisa" },
            new Banco { Id = 70, Codigo = "070", Nome = "BRB - Banco de Brasília" },
            new Banco { Id = 74, Codigo = "074", Nome = "Banco J. Safra" },
            new Banco { Id = 75, Codigo = "075", Nome = "Banco ABN Amro" },
            new Banco { Id = 76, Codigo = "076", Nome = "Banco KDB do Brasil" },
            new Banco { Id = 77, Codigo = "077", Nome = "Banco Inter" },
            new Banco { Id = 78, Codigo = "078", Nome = "Haitong Banco de Investimento" },
            new Banco { Id = 79, Codigo = "079", Nome = "Banco Original do Agronegócio" },
            new Banco { Id = 80, Codigo = "080", Nome = "B&T Corretora de Câmbio" },
            new Banco { Id = 81, Codigo = "081", Nome = "Banco Seguro (BBN)" },
            new Banco { Id = 82, Codigo = "082", Nome = "Banco Topázio" },
            new Banco { Id = 83, Codigo = "083", Nome = "Banco da China Brasil" },
            new Banco { Id = 84, Codigo = "084", Nome = "Uniprime Norte do Paraná" },
            new Banco { Id = 85, Codigo = "085", Nome = "Cooperativa Central de Crédito - Ailos" },
            new Banco { Id = 88, Codigo = "088", Nome = "Banco Randon" },
            new Banco { Id = 89, Codigo = "089", Nome = "Cooperativa de Crédito Rural da Região da Mogiana" },
            new Banco { Id = 91, Codigo = "091", Nome = "Unicred Central RS" },
            new Banco { Id = 92, Codigo = "092", Nome = "BRK Financeira" },
            new Banco { Id = 93, Codigo = "093", Nome = "Pólocred" },
            new Banco { Id = 94, Codigo = "094", Nome = "Banco Finaxis" },
            new Banco { Id = 95, Codigo = "095", Nome = "Travelex Banco de Câmbio" },
            new Banco { Id = 96, Codigo = "096", Nome = "Banco B3" },
            new Banco { Id = 97, Codigo = "097", Nome = "Cooperativa Central de Crédito Noroeste Brasileiro (CentralCredi)" },
            new Banco { Id = 98, Codigo = "098", Nome = "Credialiança Cooperativa de Crédito Rural" },
            new Banco { Id = 99, Codigo = "099", Nome = "Uniprime Central" },
            new Banco { Id = 100, Codigo = "100", Nome = "Planner Corretora de Valores" },
            new Banco { Id = 104, Codigo = "104", Nome = "Caixa Econômica Federal" },
            new Banco { Id = 107, Codigo = "107", Nome = "Banco Bocom BBM" },
            new Banco { Id = 119, Codigo = "119", Nome = "Banco Western Union" },
            new Banco { Id = 120, Codigo = "120", Nome = "Banco Rodobens" },
            new Banco { Id = 121, Codigo = "121", Nome = "Banco Agibank" },
            new Banco { Id = 125, Codigo = "125", Nome = "Banco Genial" },
            new Banco { Id = 128, Codigo = "128", Nome = "MS Bank Banco de Câmbio" },
            new Banco { Id = 136, Codigo = "136", Nome = "Unicred do Brasil" },
            new Banco { Id = 144, Codigo = "144", Nome = "Bexs Banco de Câmbio" },
            new Banco { Id = 169, Codigo = "169", Nome = "Banco Olé Consignado" },
            new Banco { Id = 184, Codigo = "184", Nome = "Banco Itaú BBA" },
            new Banco { Id = 197, Codigo = "197", Nome = "Stone Pagamentos" },
            new Banco { Id = 208, Codigo = "208", Nome = "Banco BTG Pactual" },
            new Banco { Id = 212, Codigo = "212", Nome = "Banco Original" },
            new Banco { Id = 213, Codigo = "213", Nome = "Banco Arbi" },
            new Banco { Id = 217, Codigo = "217", Nome = "Banco John Deere" },
            new Banco { Id = 218, Codigo = "218", Nome = "Banco BS2" },
            new Banco { Id = 222, Codigo = "222", Nome = "Banco Credit Agricole Brasil" },
            new Banco { Id = 224, Codigo = "224", Nome = "Banco Fibra" },
            new Banco { Id = 233, Codigo = "233", Nome = "Banco Cifra" },
            new Banco { Id = 237, Codigo = "237", Nome = "Banco Bradesco" },
            new Banco { Id = 241, Codigo = "241", Nome = "Banco Clássico" },
            new Banco { Id = 243, Codigo = "243", Nome = "Banco Máxima" },
            new Banco { Id = 246, Codigo = "246", Nome = "Banco ABC Brasil" },
            new Banco { Id = 249, Codigo = "249", Nome = "Banco Investcred Unibanco" },
            new Banco { Id = 250, Codigo = "250", Nome = "BCV - Banco de Crédito e Varejo" },
            new Banco { Id = 254, Codigo = "254", Nome = "Paraná Banco" },
            new Banco { Id = 260, Codigo = "260", Nome = "Nu Pagamentos (Nubank)" },
            new Banco { Id = 265, Codigo = "265", Nome = "Banco Fator" },
            new Banco { Id = 266, Codigo = "266", Nome = "Banco Cédula" },
            new Banco { Id = 269, Codigo = "269", Nome = "HSBC Brasil Banco Múltiplo" },
            new Banco { Id = 270, Codigo = "270", Nome = "Sagitur Corretora de Câmbio" },
            new Banco { Id = 271, Codigo = "271", Nome = "IB Corretora de Câmbio" },
            new Banco { Id = 272, Codigo = "272", Nome = "AGK Corretora de Câmbio" },
            new Banco { Id = 274, Codigo = "274", Nome = "Money Plus" },
            new Banco { Id = 276, Codigo = "276", Nome = "Banco Senff" },
            new Banco { Id = 278, Codigo = "278", Nome = "Genial Investimentos" },
            new Banco { Id = 279, Codigo = "279", Nome = "Cooperativa de Crédito Rural de Primavera do Leste" },
            new Banco { Id = 280, Codigo = "280", Nome = "Avista Financeira" },
            new Banco { Id = 281, Codigo = "281", Nome = "Cooperativa de Crédito Rural Coopavel" },
            new Banco { Id = 283, Codigo = "283", Nome = "RB Investimentos" },
            new Banco { Id = 285, Codigo = "285", Nome = "Frente Corretora de Câmbio" },
            new Banco { Id = 286, Codigo = "286", Nome = "Cooperativa de Crédito Rural de Ouro Sulcredi" },
            new Banco { Id = 288, Codigo = "288", Nome = "Carol Distribuidora" },
            new Banco { Id = 289, Codigo = "289", Nome = "Decyseo Corretora de Câmbio" },
            new Banco { Id = 290, Codigo = "290", Nome = "PagSeguro Internet" },
            new Banco { Id = 292, Codigo = "292", Nome = "BS2 Distribuidora de Títulos e Valores Mobiliários" },
            new Banco { Id = 293, Codigo = "293", Nome = "Lastro RDV" },
            new Banco { Id = 296, Codigo = "296", Nome = "Vision" },
            new Banco { Id = 299, Codigo = "299", Nome = "Banco Sorocred" },
            new Banco { Id = 300, Codigo = "300", Nome = "Banco de la Nacion Argentina" },
            new Banco { Id = 301, Codigo = "301", Nome = "BPP Instituição de Pagamento" },
            new Banco { Id = 310, Codigo = "310", Nome = "VORTX" },
            new Banco { Id = 318, Codigo = "318", Nome = "Banco BMG" },
            new Banco { Id = 320, Codigo = "320", Nome = "Banco CCB Brasil" },
            new Banco { Id = 322, Codigo = "322", Nome = "Cooperativa de Crédito de Livre Admissão (Rede)" },
            new Banco { Id = 323, Codigo = "323", Nome = "Mercado Pago" },
            new Banco { Id = 329, Codigo = "329", Nome = "QI Sociedade de Crédito Direto" },
            new Banco { Id = 330, Codigo = "330", Nome = "Banco Bari de Investimentos e Financiamentos" },
            new Banco { Id = 331, Codigo = "331", Nome = "Fram Capital" },
            new Banco { Id = 332, Codigo = "332", Nome = "Acesso Soluções de Pagamento" },
            new Banco { Id = 335, Codigo = "335", Nome = "Banco Digio" },
            new Banco { Id = 336, Codigo = "336", Nome = "Banco C6" },
            new Banco { Id = 340, Codigo = "340", Nome = "Super Pagamentos" },
            new Banco { Id = 341, Codigo = "341", Nome = "Itaú Unibanco" },
            new Banco { Id = 342, Codigo = "342", Nome = "Creditas" },
            new Banco { Id = 343, Codigo = "343", Nome = "FFA" },
            new Banco { Id = 348, Codigo = "348", Nome = "Banco XP" },
            new Banco { Id = 349, Codigo = "349", Nome = "Amaggi" },
            new Banco { Id = 352, Codigo = "352", Nome = "Toro Corretora de Títulos e Valores Mobiliários" },
            new Banco { Id = 356, Codigo = "356", Nome = "Banco ABN Amro Real (encerrado, mas código histórico)" },
            new Banco { Id = 359, Codigo = "359", Nome = "Zema Crédito Financiamento e Investimento" },
            new Banco { Id = 360, Codigo = "360", Nome = "Trinus Capital" },
            new Banco { Id = 362, Codigo = "362", Nome = "Cielo" },
            new Banco { Id = 363, Codigo = "363", Nome = "Socopa" },
            new Banco { Id = 364, Codigo = "364", Nome = "Gerencianet (Efí)" },
            new Banco { Id = 365, Codigo = "365", Nome = "Solidus" },
            new Banco { Id = 366, Codigo = "366", Nome = "Banco Société Générale Brasil" },
            new Banco { Id = 368, Codigo = "368", Nome = "Banco CSF (Carrefour)" },
            new Banco { Id = 370, Codigo = "370", Nome = "Banco Mizuho do Brasil" },
            new Banco { Id = 376, Codigo = "376", Nome = "Banco J.P. Morgan" },
            new Banco { Id = 380, Codigo = "380", Nome = "PicPay Servicos" },
            new Banco { Id = 381, Codigo = "381", Nome = "Banco Mercedes-Benz" },
            new Banco { Id = 382, Codigo = "382", Nome = "Fiducia" },
            new Banco { Id = 383, Codigo = "383", Nome = "Juno" },
            new Banco { Id = 384, Codigo = "384", Nome = "Global SCM" },
            new Banco { Id = 386, Codigo = "386", Nome = "Nu Financeira" },
            new Banco { Id = 389, Codigo = "389", Nome = "Banco Mercantil do Brasil" },
            new Banco { Id = 394, Codigo = "394", Nome = "Banco Bradesco Financiamentos" },
            new Banco { Id = 396, Codigo = "396", Nome = "HUB Pagamentos" },
            new Banco { Id = 399, Codigo = "399", Nome = "Kirton Bank" },
            new Banco { Id = 403, Codigo = "403", Nome = "Cora Sociedade de Crédito Direto" },
            new Banco { Id = 404, Codigo = "404", Nome = "Sumup Sociedade de Crédito Direto" },
            new Banco { Id = 406, Codigo = "406", Nome = "Accredito" },
            new Banco { Id = 412, Codigo = "412", Nome = "Banco Capital" },
            new Banco { Id = 422, Codigo = "422", Nome = "Banco Safra" },
            new Banco { Id = 456, Codigo = "456", Nome = "Banco MUFG Brasil" },
            new Banco { Id = 464, Codigo = "464", Nome = "Banco Sumitomo Mitsui Brasileiro" },
            new Banco { Id = 473, Codigo = "473", Nome = "Banco Caixa Geral Brasil" },
            new Banco { Id = 477, Codigo = "477", Nome = "Citibank" },
            new Banco { Id = 487, Codigo = "487", Nome = "Deutsche Bank Brasil" },
            new Banco { Id = 488, Codigo = "488", Nome = "JPMorgan Chase Bank (filial)" },
            new Banco { Id = 492, Codigo = "492", Nome = "ING Bank" },
            new Banco { Id = 505, Codigo = "505", Nome = "Banco Credit Suisse" },
            new Banco { Id = 600, Codigo = "600", Nome = "Banco Luso Brasileiro" },
            new Banco { Id = 604, Codigo = "604", Nome = "Banco Industrial do Brasil" },
            new Banco { Id = 610, Codigo = "610", Nome = "Banco VR" },
            new Banco { Id = 611, Codigo = "611", Nome = "Banco Paulista" },
            new Banco { Id = 612, Codigo = "612", Nome = "Banco Guanabara" },
            new Banco { Id = 613, Codigo = "613", Nome = "Banco Pecúnia" },
            new Banco { Id = 623, Codigo = "623", Nome = "Banco Pan" },
            new Banco { Id = 626, Codigo = "626", Nome = "Banco C6 Consignado" },
            new Banco { Id = 630, Codigo = "630", Nome = "Banco Smartbank" },
            new Banco { Id = 633, Codigo = "633", Nome = "Banco Rendimento" },
            new Banco { Id = 634, Codigo = "634", Nome = "Banco Triângulo" },
            new Banco { Id = 637, Codigo = "637", Nome = "Banco Sofisa" },
            new Banco { Id = 643, Codigo = "643", Nome = "Banco Pine" },
            new Banco { Id = 652, Codigo = "652", Nome = "Itaú Unibanco Holding" },
            new Banco { Id = 653, Codigo = "653", Nome = "Banco Indusval" },
            new Banco { Id = 654, Codigo = "654", Nome = "Banco A.J. Renner" },
            new Banco { Id = 655, Codigo = "655", Nome = "Banco Votorantim" },
            new Banco { Id = 707, Codigo = "707", Nome = "Banco Daycoval" },
            new Banco { Id = 712, Codigo = "712", Nome = "Banco Ourinvest" },
            new Banco { Id = 739, Codigo = "739", Nome = "Banco Cetelem" },
            new Banco { Id = 741, Codigo = "741", Nome = "Banco Ribeirão Preto" },
            new Banco { Id = 743, Codigo = "743", Nome = "Banco Semear" },
            new Banco { Id = 745, Codigo = "745", Nome = "Banco Citibank" },
            new Banco { Id = 746, Codigo = "746", Nome = "Banco Modal" },
            new Banco { Id = 747, Codigo = "747", Nome = "Banco Rabobank Internacional Brasil" },
            new Banco { Id = 748, Codigo = "748", Nome = "Banco Cooperativo Sicredi" },
            new Banco { Id = 751, Codigo = "751", Nome = "Scotiabank Brasil Banco Múltiplo" },
            new Banco { Id = 752, Codigo = "752", Nome = "Banco BNP Paribas Brasil" },
            new Banco { Id = 753, Codigo = "753", Nome = "Banco Comercial Uruguai (NBC Bank Brasil)" },
            new Banco { Id = 754, Codigo = "754", Nome = "Banco Sistema" },
            new Banco { Id = 755, Codigo = "755", Nome = "Bank of America Merrill Lynch Banco Múltiplo" },
            new Banco { Id = 756, Codigo = "756", Nome = "Banco Cooperativo do Brasil (Bancoob/Sicoob)" },
            new Banco { Id = 757, Codigo = "757", Nome = "Banco KEB Hana do Brasil" }
        );
    }
}
